//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShareArtEntities : DbContext
    {
        public ShareArtEntities()
            : base("name=ShareArtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CourseTbl> CourseTbls { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TuteeTbl> TuteeTbls { get; set; }
        public DbSet<TutorTbl> TutorTbls { get; set; }
    }
}
