//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TuteeTbl
    {
        public TuteeTbl()
        {
            this.CourseTbls = new HashSet<CourseTbl>();
            this.TutorTbls = new HashSet<TutorTbl>();
        }
    
        public int TuteeId { get; set; }
        public string TuteeFullName { get; set; }
        public string TuteePassword { get; set; }
        public string TuteeUsername { get; set; }
    
        public virtual ICollection<CourseTbl> CourseTbls { get; set; }
        public virtual ICollection<TutorTbl> TutorTbls { get; set; }
    }
}
