//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorTbl
    {
        public TutorTbl()
        {
            this.CourseTbls = new HashSet<CourseTbl>();
            this.TuteeTbls = new HashSet<TuteeTbl>();
        }
    
        public int TutorId { get; set; }
        public string TutorFullName { get; set; }
        public string TutorPassword { get; set; }
        public string TutorUsername { get; set; }
    
        public virtual ICollection<CourseTbl> CourseTbls { get; set; }
        public virtual ICollection<TuteeTbl> TuteeTbls { get; set; }
    }
}
